# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Promethean Dreams
tagline:          The feel of life as a scientist primitive
url:              https://the-700nm-physicist.github.io/
paginate:         1
baseurl:          /
#author:
 # name:           
  #url:            
  #email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/The-700nm-Physicist/The-700nm-Physicist.github.io 
